name: Code Quality (WP Standards)

on:
  workflow_call: # Enables remote calls from other repos

jobs:
  lint:
    name: Check Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PHP Coding Standards (10up)
        uses: 10up/wpcs-action@stable
        with:
          # Uses 10up-Default or WordPress standards automatically
          standard: 'WordPress' 

      - name: JavaScript & CSS Linting
        run: |
          npm install @wordpress/eslint-plugin @wordpress/stylelint-config stylelint eslint --save-dev
          npx eslint . --ignore-pattern '**/minified/**'
          npx stylelint "**/*.css" --ignore-path '**/minified/**'
